#!/bin/bash

set -e

LIMIT=2

echo '## Recent runs'

gh workflow list --json name --jq .[].name | while read -r workflow; do
    echo "### $workflow"

    echo '| conclusion/status | databaseId | event | createdAt | startedAt | updatedAt |'
    echo '| ----------------- | ---------- | ----- | --------- | --------- | --------- |'
    gh run list --limit "$LIMIT" --workflow "$workflow" --json databaseId --jq '.[].databaseId' | while read -r run; do
        eval "$(gh run view "$run" --json conclusion,status,databaseId,url,event,createdAt,startedAt,updatedAt --jq 'to_entries | .[] | .key + "=" + (.value | @sh)')"
        case "$conclusion" in
            success)
                conclusion=':white_check_mark: success'
            ;;
            failure)
                conclusion=':x: failure'
            ;;
            cancelled)
                conclusion=':no_entry_sign: cancelled'
            ;;
            '')
                # When the conclusion is empty, it's not finished yet.
                # Use the status such as queued/in_progress instead.
                # shellcheck disable=SC2154
                conclusion=":yellow_circle: $status"
            ;;
        esac
        # shellcheck disable=SC2154
        echo "| $conclusion | [$databaseId]($url) | $event | $createdAt | $startedAt | $updatedAt |"
    done
done
