#!/bin/bash

set -e

LIMIT=10

echo '## Recent runs'

gh workflow list --json name --jq .[].name | while read -r workflow; do
    echo "### $workflow"

    header='| conclusion/status | databaseId | event | createdAt | startedAt | updatedAt |'
    border='| ----------------- | ---------- | ----- | --------- | --------- | --------- |'
    # search for a succeeded workflow first, it must have data of all steps
    latest_run_id="$(gh run list --limit 1 --status success --workflow "$workflow" --json databaseId --jq '.[].databaseId')"
    if [ -z "$latest_run_id" ]; then
        # try for a failed workflow next, it should have the definition of all steps
        latest_run_id="$(gh run list --limit 1 --status failure --workflow "$workflow" --json databaseId --jq '.[].databaseId')"
    fi
    if [ -z "$latest_run_id" ]; then
        # fall back to any completed job even if it was cancelled
        latest_run_id="$(gh run list --limit 1 --status completed --workflow "$workflow" --json databaseId --jq '.[].databaseId')"
    fi
    # for simplicity, use only the last job defined
    gh run view "$latest_run_id" --json jobs --jq '.jobs[-1].steps[].name' | { while read -r step; do
        header="$(printf '%s %s |' "$header" "$step")"
        border="$(printf '%s -- |' "$border")"
    done
    echo "$header"
    echo "$border"
    }
    gh run list --limit "$LIMIT" --workflow "$workflow" --json databaseId --jq '.[].databaseId' | while read -r run; do
        eval "$(gh run view "$run" --json conclusion,status,databaseId,url,event,createdAt,startedAt,updatedAt --jq 'to_entries.[] | .key + "=" + (.value | @sh)')"
        case "$conclusion" in
            success)
                conclusion='✅ success'
            ;;
            failure)
                conclusion='❌ failure'
            ;;
            cancelled)
                conclusion='🚫 cancelled'
            ;;
            '')
                # When the conclusion is empty, it's not finished yet.
                # Use the status such as queued/in_progress instead.
                # shellcheck disable=SC2154
                conclusion="🟡 $status"
            ;;
        esac
        # shellcheck disable=SC2154
        result="| $conclusion | [$databaseId]($url) | $event | $createdAt | $startedAt | $updatedAt |"
        steps=$(gh run view "$run" --json jobs --jq '.jobs[-1].steps[]')
        gh run view "$latest_run_id" --json jobs --jq '.jobs[-1].steps[].name' | { while read -r step_name; do
            step_conclusion="$(echo "$steps" | jq -r "select(.name==\"$step_name\").conclusion")"
            case "$step_conclusion" in
                success)
                    step_conclusion='✅'
                ;;
                failure)
                    step_conclusion='❌'
                ;;
                skipped)
                    step_conclusion='⏩'
                ;;
                cancelled)
                    step_conclusion='🚫'
                ;;
            esac
            result="$(printf '%s %s |' "$result" "$step_conclusion")"
        done
        echo "$result"
        }
    done
done
