#!/bin/bash

set -e
[ "$RUNNER_DEBUG" = 1 ] && set -x
set -u

LIMIT=10
LOG_LINES_MORE=9

echo '## Recent runs'

header='| conclusion/status | databaseId | event | createdAt<br>startedAt<br>updatedAt |'
border='| ----------------- | ---------- | ----- | ----------------------------------- |'

gh workflow list --json name --jq .[].name | while read -r workflow; do
    echo "### $workflow"

    # search for a succeeded or failed workflow first, it must have data of all steps
    latest_run_id="$(gh run list --workflow "$workflow" --status completed \
        --json databaseId,conclusion \
        --jq '[ .[] | select(.conclusion | test("^(success|failure)$")) ] | first.databaseId')"
    if [ -z "$latest_run_id" ]; then
        # fall back to any completed job even if it was cancelled
        latest_run_id="$(gh run list --limit 1 --status completed --workflow "$workflow" --json databaseId --jq '.[].databaseId')"
    fi
    # for simplicity, use only the last job defined
    # and skip "cannot iterate over: null"
    step_names="$(gh run view "$latest_run_id" --json jobs --jq '.jobs[-1].steps[].name' || true)"
    echo "$step_names" | { while read -r step_name; do
        [ -z "$step_name" ] && continue
        header="$(printf '%s %s |' "$header" "$step_name")"
        border="$(printf '%s -- |' "$border")"
    done
    # add the failed log column
    printf '%s log-failed |\n' "$header"
    printf '%s ---------- |\n' "$border"
    }
    gh run list --limit "$LIMIT" --workflow "$workflow" --json databaseId --jq '.[].databaseId' | while read -r run; do
        eval "$(gh run view "$run" --json conclusion,status,databaseId,url,event,createdAt,startedAt,updatedAt --jq 'to_entries.[] | .key + "=" + (.value | @sh)')"
        log=
        case "$conclusion" in
            success)
                conclusion='✅ success'
            ;;
            failure)
                conclusion='❌ failure'
                log="$(gh run view "$run" --log-failed || true)"
                # extract log lines by cutting the timestamp from
                # "JOB_HEADER 2025-05-15T15:34:10.8396378Z LOG_LINE"
                log="$(echo "$log" | sed -e 's/.*\.[0-9]\{7\}Z //')"
                # show the last LOG_LINES from the first error.
                # the second error and on can be in a log collection phase for example.
                log="$(echo "$log" | grep -m1 -B "$LOG_LINES_MORE" '^##\[error\]' || true)"
                # format as HTML in Markdown
                log="$(echo "$log" | sed -e 's/$/<br>/')"
                # remove line breaks to fit into a Markdown table
                log="$(echo "$log" | tr -d '\n')"
                log="<details><pre>${log}</pre></details>"
            ;;
            cancelled)
                conclusion='🚫 cancelled'
            ;;
            '')
                # When the conclusion is empty, it's not finished yet.
                # Use the status such as queued/in_progress instead.
                # shellcheck disable=SC2154
                conclusion="🟡 $status"
            ;;
        esac
        # shellcheck disable=SC2154
        result="| $conclusion | [$databaseId]($url) | $event | <details>${createdAt}<br>${startedAt}<br>${updatedAt}</details> |"

        # when there is no step run yet, it will error out with "cannot iterate over: null"
        steps="$(gh run view "$run" --json jobs --jq '.jobs[-1].steps[]' || true)"
        echo "$step_names" | { while read -r step_name; do
            [ -z "$step_name" ] && continue
            step_conclusion="$(echo "$steps" | jq -r "select(.name==\"$step_name\").conclusion")"
            case "$step_conclusion" in
                success)
                    step_conclusion='✅'
                ;;
                failure)
                    step_conclusion='❌'
                ;;
                skipped)
                    # "⏩" can be too distracting
                    step_conclusion='⊘'
                ;;
                cancelled)
                    step_conclusion='🚫'
                ;;
            esac
            result="$(printf '%s %s |' "$result" "$step_conclusion")"
        done
        printf '%s %s |\n' "$result" "$log"
        }
    done
done
