name: "LP: #2104066"

on:
  workflow_dispatch:
    inputs:

  schedule:
    - cron: '*/17 * * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: true

permissions:
  contents: read

env:
  COLUMNS: 160  # default: 80
  DEBIAN_FRONTEND: noninteractive

defaults:
  run:
    shell: bash -ex {0}

jobs:
  snapd:
    runs-on: [self-hosted, linux, AMD64, X64, medium, noble]
    steps:
      - name: Host snapd current status
        run: |
          apt-cache policy snapd
          snap list
          snap version
      - name: Install LXD
        run: |
          sudo snap install lxd
      - name: Launch LXD container
        run: |
          lxc launch ubuntu:noble snap-test1
      - name: Guest snapd current status
        run: |
          lxc exec snap-test1 -- '
              snap install openstack
              apt-cache policy snapd
              snap list
              snap version
          '
      - name: Install a snap inside the guest
        run: |
          lxc exec snap-test1 -- snap install openstack
