name: Click to see a report

on:
  workflow_dispatch:

  schedule:
    - cron: '21 22 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  report:
    name: Report
    runs-on: [self-hosted, linux, AMD64, X64, large, noble]
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Recent runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          shellcheck .github/assets/workflows/report-recent-runs
          .github/assets/workflows/report-recent-runs >> "$GITHUB_STEP_SUMMARY"
