name: Sunbeam Single-node guided

on:
  #push:
  #  branches: ["act"]

  workflow_dispatch:
    inputs:
      use_workaround:
        description: 'Apply a workaround'
        required: true
        default: true
        type: boolean
      hardware_profile:
        description: 'Specs for each machine'
        required: true
        default: tutorial
        type: choice
        options:
          - tutorial

permissions:
  contents: read

env:
  COLUMNS: 160  # default: 80
  DEBIAN_FRONTEND: noninteractive
  # github.event.inputs.use_workaround returns a string
  # - non-empty 'true' or 'false' from the workflow_dispatch
  # - '' from the on-push event
  # set the default value as true only when there is no input
  USE_WORKAROUND: ${{ github.event.inputs.use_workaround || true }}
  HARDWARE_PROFILE: ${{ inputs.hardware_profile || 'tutorial' }}

defaults:
  run:
    # act doesn't show a good summary of elapsed time of each step, and
    # having an unnecessary `bash -e -c` at the beginning is for
    # actionlint to activate shellcheck.
    shell: bash -e -c '/usr/bin/time -f "\nStep total time:\t%E" bash -ex {0}'

jobs:
  actionlint:
    runs-on: [self-hosted, linux, AMD64, X64, medium, noble]
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        if: ${{ !env.ACT }}
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Install prerequisites for actionlint
        if: ${{ !env.ACT }}
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Check workflow files
        run: |
          # use a local binary if env.ACT
          ${{ steps.get_actionlint.outputs.executable || 'actionlint' }} -color \
              .github/workflows/single-node-guided.yml
  single-node-guided-tutorial:
    name: Single-node Guided Tutorial
    runs-on: [self-hosted, linux, AMD64, X64, large, noble]
    needs: actionlint
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: |
          if [ "$USE_WORKAROUND" = true ]; then
              echo '::warning::Not a clean run. Some workarounds are going to be used.'
          fi
          case "$HARDWARE_PROFILE" in
              tutorial)
                  # https://canonical.com/microstack/docs/single-node-guided
                  echo CPU=4             >> "$GITHUB_ENV"
                  echo MEMORY=16         >> "$GITHUB_ENV"
                  echo DISK=100          >> "$GITHUB_ENV"
              ;;
              *)
                  echo '::error:: Invalid hardware profile'
                  exit 1
              ;;
          esac
          # FIXME: use $GITHUB_STEP_SUMMARY
          # shellcheck source=/dev/null
          source "$GITHUB_ENV"
          echo "::notice::Selected hardware profile: ${HARDWARE_PROFILE}.%0ACPU: ${CPU}%0AMEMORY: ${MEMORY}%0ADISK: ${DISK}"
      - name: Check machine specs
        run: |
          # bare metal returns "none" with exit 1
          systemd-detect-virt || true
          cat /etc/os-release
          lscpu
          free -h
          lsblk
          lsblk -f
          if [ "$ACTIONS_STEP_DEBUG" = true ]; then
              # IPv6 address can be sensitive
              ip -br a
              ip r
              resolvectl --no-pager
          fi
      # TODO: check if greenfield or brownfield first
      - name: Install prerequisites
        if: ${{ !env.ACT }}
        run: |
          sudo apt-get update
          sudo apt-get install -y uvtool j2cli
          # make sure the default user is in the libvirt group.
          # the "runner" user in Github workflow is not in the sudo
          # group so it's not automatically added into the libvirt
          # group.
          sudo adduser "$USER" libvirt
      - name: Download a VM image
        if: ${{ !env.ACT }}
        run: |
          sudo -g libvirt uvt-simplestreams-libvirt sync release=noble arch=amd64
          sudo -g libvirt uvt-simplestreams-libvirt query
      - name: Prepare SSH, virtual network bridge
        if: ${{ !env.ACT }}
        run: |
          # SSH
          ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ''
          cat .github/assets/workflows/ssh_config | tee -a ~/.ssh/config

          # bridge
          sudo -g libvirt virsh -c qemu:///system net-define .github/assets/workflows/sunbeam-virbr0.xml
          sudo -g libvirt virsh -c qemu:///system net-autostart sunbeam-virbr0
          sudo -g libvirt virsh -c qemu:///system net-start sunbeam-virbr0
      - name: Clean up previous virtual machines
        if: ${{ env.ACT }}
        run: |
          # FIXME: the requirement of FQDN is not documented well in each tutorial
          sudo -g libvirt uvt-kvm destroy sunbeam-single-node-guided.localdomain || true
          ssh-keygen -R 192.168.124.21 || true
      - name: Prepare a virtual machine
        run: |
          sudo -g libvirt uvt-kvm create \
              --machine-type q35 \
              --cpu "$CPU" \
              --host-passthrough \
              --memory "$((MEMORY * 1024))" \
              --disk "$DISK" \
              --unsafe-caching \
              --bridge sunbeam-virbr0 \
              --network-config /dev/stdin \
              --ssh-public-key-file ~/.ssh/id_ed25519.pub \
              --no-start \
              sunbeam-single-node-guided.localdomain \
              release=noble <<EOF
          network:
            version: 2
            ethernets:
              enp1s0:
                dhcp4: false
                dhcp6: false
                accept-ra: false
                addresses:
                  - 192.168.124.21/24
                routes:
                  - to: default
                    via: 192.168.124.1
                nameservers:
                  addresses:
                    - 192.168.124.1
          EOF

          # secondary NIC
          sudo -g libvirt virsh -c qemu:///system attach-interface sunbeam-single-node-guided.localdomain \
              network sunbeam-virbr0 \
              --model virtio --config

          sudo -g libvirt virsh -c qemu:///system start sunbeam-single-node-guided.localdomain

          until ssh -oStrictHostKeyChecking=no sunbeam-single-node-guided -- 'cloud-init status --wait; ip -br a; lsblk'; do
              sleep 5
          done

          # LP: #2065911
          if [ "$USE_WORKAROUND" = true ]; then
              echo '::warning::Workaround for https://launchpad.net/bugs/2065911'
              ssh sunbeam-single-node-guided -- 'sudo install -m 0600 /dev/stdin /etc/netplan/90-local-ovs-ext-port.yaml <<EOF
          network:
            version: 2
            ethernets:
              # LP: #2065911
              enp7s0:
                dhcp4: false
                dhcp6: false
                accept-ra: false
          EOF
                  sudo netplan apply
              '
          fi
      - name: Sunbeam - Prepare manifest file
        run: |
          if [ "$USE_WORKAROUND" = true ]; then
              echo '::warning::Workaround for https://launchpad.net/bugs/2098163'
              echo '::warning::Workaround for https://launchpad.net/bugs/2098438'
          fi
          j2 -f yaml -o ./manifest.yaml .github/assets/workflows/single-node-guided/manifest.yaml.j2 - <<EOF
          use_workaround: $USE_WORKAROUND
          dockerhub_mirror: $DOCKERHUB_MIRROR
          EOF
          scp ./manifest.yaml sunbeam-single-node-guided:
      - name: Sunbeam - Prepare the machine
        run: |
          ssh sunbeam-single-node-guided -- sudo snap install openstack --channel 2024.1/edge
          ssh sunbeam-single-node-guided -- 'sunbeam prepare-node-script --bootstrap | bash -x'
      - name: Sunbeam - Bootstrap the cloud
        run: |
          # -t is necessary to see some progress in act env, LP: #2097451
          # Also, without -t, somehow add-k8s command gets stuck in act env
          # although it doesn't happen in GitHub runner.
          # without -tt, GitHub runner's log should be quiet.
          ssh sunbeam-single-node-guided -t -- sunbeam cluster bootstrap --manifest manifest.yaml
      - name: Sunbeam - Configure the cloud
        run: |
          ssh sunbeam-single-node-guided -t -- sunbeam configure --openrc demo-openrc
      - name: Sunbeam - Launch a VM
        run: |
          ssh sunbeam-single-node-guided -t -- sunbeam launch ubuntu --name test
      - name: Sunbeam - Connect to the VM
        run: |
          # The cloud-init process inside the VM takes ~2 minutes to bring up the
          # SSH service after the VM gets ACTIVE in OpenStack
          sleep 5m
          ssh sunbeam-single-node-guided -- '
              set -ex
              source demo-openrc
              demo_floating_ip="$(openstack floating ip list -c Floating\ IP\ Address -f value | head -n1)"
              ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i ~/snap/openstack/current/sunbeam "ubuntu@${demo_floating_ip}" -- cloud-init status --wait
          '
      - name: Save admin-openrc
        run: |
          ssh sunbeam-single-node-guided -t -- 'sunbeam openrc > admin-openrc'
      - name: Smoke testing - Host reboot
        run: |
          ssh sunbeam-single-node-guided -- sudo reboot
          # wait some time to settle
          sleep 15m
          ssh sunbeam-single-node-guided -t -- '
              set -ex
              uptime -p
              sunbeam launch ubuntu --name test-after-reboot
              sleep 5m
              source demo-openrc
              ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i ~/snap/openstack/current/sunbeam -l ubuntu \
                  "$(openstack server show test-after-reboot --format yaml | grep -E -o 192\.168\.124\.[0-9]+)" -- cloud-init status --wait
          '
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: manifest.yaml
          path: ./manifest.yaml
