name: Testflinger - Multi-node

on:
  workflow_dispatch:

  #schedule:
  #  - cron: '17 17 */3 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: true

permissions:
  contents: read

jobs:
  testflinger-multi-node-how-to:
    name: Testflinger - Multi-node How-to Guide
    runs-on: [self-hosted, testflinger]
    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          path: repository
      - name: Pack the repository
        run: |
          tar acf repository.tar.gz repository/
      - name: Submit job
        uses: canonical/testflinger/.github/actions/submit@5182b45a313bc0dc75296d1f79da06b4c44cb4e3 # main
        with:
          poll: true
          job: |
            job_queue: hinopio
            provision_data:
              # noble has duplicate deb line warnings
              distro: noble
              #kernel: hwe-24.04
            global_timeout: 21600  # 6 hours
            output_timeout: 5400  # 90 min
            test_data:
              attachments:
                - local: repository.tar.gz
              test_cmds: |
                set -ex
                scp ./attachments/test/repository.tar.gz "ubuntu@${DEVICE_IP}:"
                if ssh "ubuntu@${DEVICE_IP}" '
                    set -ex
                    tar xf repository.tar.gz
                    cd repository/
                    # LP: #2093303
                    sudo mv -v /etc/apt/sources.list{,.bak}
                    sudo apt-get update
                    sudo apt-get install -y make
                    make prerequisites
                    # include ~/.local/bin in PATH
                    source  ~/.profile
                    set -o pipefail
                    # LP: #2097451
                    # LP: #2102175
                    make multi-node | (grep --line-buffered -v '[⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏]' || true)
                '; then
                    scp -r "ubuntu@${DEVICE_IP}:repository/artifacts/" artifacts/ || true
                    find artifacts/
                else
                    scp -r "ubuntu@${DEVICE_IP}:repository/artifacts/" artifacts/ || true
                    find artifacts/
                    exit 1
                fi
