name: Submit a job to Testflinger

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testflinger-submit:
    runs-on: [self-hosted, testflinger]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          - path: repository
      - name: Pack the repository
        run: |
          tar acvf repository.tar.gz repository/
      - name: Submit job
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job: |
            job_queue: beldam
            provision_data:
              # noble has duplicate deb line warnings
              distro: jammy
              kernel: hwe-22.04
            test_data:
              attachments:
                - local: repository.tar.gz
              test_cmds: |
                set -x
                pwd
                env
                tar xvf ./attachments/repository.tar.gz
                ls -alR
                false
                echo 'false was ignored'
