name: Testflinger - Single-node How-to Guide

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testflinger-submit:
    runs-on: [self-hosted, testflinger]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: repository
      - name: Pack the repository
        run: |
          tar acf repository.tar.gz repository/
      - name: Submit job
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job: |
            job_queue: beldam
            provision_data:
              # noble has duplicate deb line warnings
              distro: noble
              #kernel: hwe-24.04
            output_timeout: 7200  # 120 min
            test_data:
              attachments:
                - local: repository.tar.gz
              test_cmds: |
                set -ex
                scp ./attachments/test/repository.tar.gz "ubuntu@\${DEVICE_IP}:"
                ssh -t "ubuntu@\${DEVICE_IP}" '
                    set -ex
                    tar xf repository.tar.gz
                    cd repository/
                    sudo apt-get -q update
                    sudo apt-get -q install -y make
                    make prerequisites
                    # include ~/.local/bin in PATH
                    source  ~/.profile
                    make single-node
                '
                # TODO: scp artifacts
