name: Testflinger - SSH

on:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash -ex {0}

jobs:
  testflinger-ssh:
    name: Testflinger - SSH
    runs-on: [self-hosted, testflinger]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Reserve a Testflinger machine
        id: testflinger_reserve
        if: ${{ !env.ACT && contains(fromJson(github.jobs.testflinger-ssh.runs-on), 'testflinger') }}
        # https://github.com/canonical/testflinger/issues/528
        #uses: canonical/testflinger/.github/actions/submit@main
        uses: nobuto-m/testflinger/.github/actions/submit@actions-submit-retrieve-ip
        with:
          poll: true
          job: |
            job_queue: beldam
            provision_data:
              # noble has duplicate deb line warnings
              distro: noble
              #kernel: hwe-24.04
            reserve_data:
              #timeout: 21600  # 6 hours
              timeout: 1200  # 20 min
      - name: Run some local commands
        run: |
          systemd-detect-virt || true
          env
          lscpu
          free -h
          lsblk -e7
          ip -br a
          ip r
      - name: Run some SSH commands
        run: |
          ssh "ubuntu@${{ steps.testflinger_reserve.outputs.device-ip }}" -- '
              set -x
              systemd-detect-virt || true
              env
              lscpu
              free -h
              lsblk -e7
          '
      - name: Release the Testflinger machine
        if: ${{ always() && !env.ACT && contains(fromJson(github.jobs.testflinger-ssh.runs-on), 'testflinger') }}
        run: |
          testflinger cancel "${{ steps.testflinger_reserve.outputs.id }}" || true
