name: Test Summary

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

defaults:
  run:
    shell: bash -ex {0}

jobs:
  report:
    runs-on: [self-hosted, linux, AMD64, X64, large, noble]
    steps:
      - name: Recent Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .github/assets/workflows/report-recent-runs.sh >> "$GITHUB_STEP_SUMMARY"
