name: Submit a test job to Testflinger
on:
  workflow_dispatch:
jobs:
  testflinger-submit:
    runs-on: [self-hosted, testflinger]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Submit job
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job: |
            job_queue: beldam
            test_data:
              test_cmds: |
                #!/usr/bin/env bash
                set -x
                pwd
                ls -alR
