name: Testflinger - SSH

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash -ex {0}

jobs:
  testflinger-ssh:
    name: Testflinger - SSH
    runs-on: [self-hosted, tutorial]
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup SSH key
        env:
          SSH_KEY_ID_ED25519: "${{ secrets.ID_ED25519_SUNBEAM_TUTORIAL_TESTS_BOT }}"
        run: |
          echo "$SSH_KEY_ID_ED25519" | install -m 0600 /dev/stdin ~/.ssh/id_ed25519
      - name: Reserve a Testflinger machine
        id: testflinger_reserve
        if: ${{ !env.ACT }}
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job: |
            job_queue: beldam
            provision_data:
              # noble has duplicate deb line warnings
              distro: noble
              #kernel: hwe-24.04
            reserve_data:
              #timeout: 21600  # 6 hours
              timeout: 1200  # 20 min
              ssh_keys:
                - lp:sunbeam-tutorial-tests-bot
      - name: Run some local commands
        run: |
          systemd-detect-virt || true
          env
          lscpu
          free -h
          lsblk -e7
          ip -br a
          ip r
      - name: Run some SSH commands
        if: ${{ !env.ACT }}
        run: |
          ssh -oStrictHostKeyChecking=no "ubuntu@${{ steps.testflinger_reserve.outputs.device-ip }}" -- '
              set -x
              systemd-detect-virt || true
              env
              lscpu
              free -h
              lsblk -e7
          '
      - name: Release the Testflinger machine
        if: ${{ always() && steps.testflinger_reserve.outputs.id }}
        run: |
          testflinger cancel "${{ steps.testflinger_reserve.outputs.id }}"
